workflows:
  android-debug:
    name: Android Debug
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - android_sdk
    working_directory: app
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - build/outputs/apk/debug/*.apk
      
